name: Build iOS App
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Permette esecuzione manuale

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Generate app icons
      run: flutter pub run flutter_launcher_icons:main
      
    - name: Install CocoaPods
      run: |
        cd ios
        pod install
        
    - name: Build iOS (Debug)
      run: flutter build ios --debug --no-codesign
      
    - name: Archive iOS app
      run: |
        cd ios
        xcodebuild -workspace Runner.xcworkspace \
          -scheme Runner \
          -configuration Debug \
          -destination generic/platform=iOS \
          -archivePath Runner.xcarchive \
          archive
          
    - name: Export IPA
      run: |
        cd ios
        xcodebuild -exportArchive \
          -archivePath Runner.xcarchive \
          -exportPath exports \
          -exportOptionsPlist ../export_options.plist
          
    - name: Upload IPA artifact
      uses: actions/upload-artifact@v3
      with:
        name: SOMMACUSTOZA-FC-iOS
        path: ios/exports/*.ipa
        
    - name: Upload dSYM artifacts
      uses: actions/upload-artifact@v3
      with:
        name: SOMMACUSTOZA-FC-dSYMs
        path: ios/exports/*.dSYM.zip
