name: sommacustoza
description: App per la gestione della squadra di calcio SOMMACUSTOZA08
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # UI & Design
  cupertino_icons: ^1.0.6
  flutter_animate: ^4.5.0
  animations: ^2.0.8
  lottie: ^3.3.1
  flutter_staggered_animations: ^1.1.1
  flutter_card_swiper: ^7.0.2
  
  # Database & Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  
  # Calendar & DateTime
  table_calendar: ^3.0.9
  intl: ^0.20.2
  
  # Network & API
  dio: ^5.4.0
  connectivity_plus: ^6.1.5
  
  # Utils
  permission_handler: ^12.0.1
  image_picker: ^1.0.5
  share_plus: ^11.1.0
  url_launcher: ^6.2.2
  
  # Charts & Graphics
  fl_chart: ^1.0.0
  
  # File handling
  path_provider: ^2.1.2
  csv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.13.1

# Configurazione icona app
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#1976D2"
    theme_color: "#1976D2"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/
